import { APP_AUTH_EXAMPLES, APP_AUTH_PREVIEWS } from './previews-app-auth';
import { APP_COURIER_EXAMPLES, APP_COURIER_PREVIEWS } from './previews-app-courier';
import { APP_DATA_EXAMPLES, APP_DATA_PREVIEWS } from './previews-app-data';
import { APP_GARAGE_EXAMPLES, APP_GARAGE_PREVIEWS } from './previews-app-garage';
import { APP_LAYOUT_EXAMPLES, APP_LAYOUT_PREVIEWS } from './previews-app-layout';
import { APP_LEDGER_EXAMPLES, APP_LEDGER_PREVIEWS } from './previews-app-ledger';
import { APP_SAAS_EXAMPLES, APP_SAAS_PREVIEWS } from './previews-app-saas';

export const APP_PREVIEWS = { ...APP_LAYOUT_PREVIEWS, ...APP_AUTH_PREVIEWS, ...APP_DATA_PREVIEWS, ...APP_SAAS_PREVIEWS, ...APP_COURIER_PREVIEWS, ...APP_GARAGE_PREVIEWS, ...APP_LEDGER_PREVIEWS };
export const APP_EXAMPLES = { ...APP_LAYOUT_EXAMPLES, ...APP_AUTH_EXAMPLES, ...APP_DATA_EXAMPLES, ...APP_SAAS_EXAMPLES, ...APP_COURIER_EXAMPLES, ...APP_GARAGE_EXAMPLES, ...APP_LEDGER_EXAMPLES };
